language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "14"
  - "12"
  - "10"
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: |
          npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
